/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FreshPackage;

import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author subedipiyush
 */
public class RatingsPanel extends javax.swing.JPanel {

    /**
     * Creates new form RatingsPanel
     */
    JLabel fitnessValue;
    JButton calcFitness,nextGeneration;
    JLabel bg_label,eyes_label,nose_label,mouth_label,forehead_label;
    JComboBox bg_rating,eyes_rating,nose_rating,mouth_rating,forehead_rating;
    int fintessValue_x = 245,fitnessValue_y = 35;
    
    public RatingsPanel(Main parent) {
        //initComponents();
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        
        List<Integer> ratings = new ArrayList<Integer>();
        for(int x=0;x<=100;x+=10)
            ratings.add(x);
        
        JLabel fitness_label = new JLabel("Fitness:");
        
               
        bg_label = new JLabel("Background");
        eyes_label = new JLabel("Eyes");
        nose_label = new JLabel("Nose");
        mouth_label = new JLabel("Mouth");
        forehead_label = new JLabel("Forehead");
        
        bg_rating = new JComboBox(ratings.toArray());
        eyes_rating = new JComboBox(ratings.toArray());
        nose_rating = new JComboBox(ratings.toArray());
        mouth_rating = new JComboBox(ratings.toArray());
        forehead_rating = new JComboBox(ratings.toArray());
        
        calcFitness = new JButton("Calculate");
        nextGeneration = new JButton("Generate");
        
        fitness_label.setLocation(220,30);
        fitness_label.setSize(180,50);
        fitness_label.setFont(new Font("Serif",Font.BOLD,30));
        
        bg_label.setLocation(5, 5);
        bg_label.setSize(new Dimension(150, 50));
        bg_label.setFont(new Font("Serif",Font.BOLD,20));
        eyes_label.setLocation(5, 35);
        eyes_label.setSize(new Dimension(150, 50));
        eyes_label.setFont(new Font("Serif",Font.BOLD,20));
        nose_label.setLocation(5, 65);
        nose_label.setSize(new Dimension(150, 50));
        nose_label.setFont(new Font("Serif",Font.BOLD,20));
        mouth_label.setLocation(5,95);
        mouth_label.setSize(new Dimension(150, 50));
        mouth_label.setFont(new Font("Serif",Font.BOLD,20));
        forehead_label.setLocation(5, 125);
        forehead_label.setSize(new Dimension(150, 50));
        forehead_label.setFont(new Font("Serif",Font.BOLD,20));
        
        bg_rating.setLocation(120,13);
        bg_rating.setSize(80,30);
        eyes_rating.setLocation(120,43);
        eyes_rating.setSize(80,30);
        nose_rating.setLocation(120,73);
        nose_rating.setSize(80,30);
        mouth_rating.setLocation(120,103);
        mouth_rating.setSize(80,30);
        forehead_rating.setLocation(120,133);
        forehead_rating.setSize(80,30);
        
        calcFitness.setLocation(5,180);
        calcFitness.setSize(80,40);
        nextGeneration.setLocation(220,180);
        nextGeneration.setSize(80,40);        
                
        fitnessValue = new JLabel("");
        fitnessValue.setSize(80,80);
        fitnessValue.setFont(new Font("Serif",Font.BOLD,25));
        fitnessValue.setLocation(247,65);
        
        add(fitness_label);
        add(fitnessValue);
        add(bg_label);
        add(eyes_label);
        add(nose_label);
        add(mouth_label);
        add(forehead_label);
        
        add(bg_rating);
        add(eyes_rating);
        add(nose_rating);
        add(mouth_rating);
        add(forehead_rating);
        
        add(calcFitness);
        add(nextGeneration);
        calcFitness.setActionCommand("Calculate");
        nextGeneration.setActionCommand("NextGeneration");
        calcFitness.addActionListener(parent);
        nextGeneration.addActionListener(parent);
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
