/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectFace;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author subedipiyush
 */
public class jPanel1 extends javax.swing.JPanel{

    /**
     * Creates new form jPanel1
     */
    String a[] = {"1","2","3","4","5","6","7","8","9","10","11","12"};
    static int index = 0;
    BufferedImage image;
    JButton jButton1;
    JLabel imagelabel = new JLabel();
    //imagelabel.addMouseListener(this);
    int x,y;
    boolean clicked = false;
    
    public jPanel1() {
        initComponents();
        setPreferredSize(new Dimension(200, 230));
        jButton1 = new JButton("Next");
        add(jButton1);
        add(imagelabel);
        
        jButton1.setLayout(null);
        jButton1.setLocation(120, 180);
        jButton1.setSize(60,30);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        setImage(index);
        imagelabel.addMouseListener(new java.awt.event.MouseAdapter() {
                        @Override
                        public void mouseClicked(java.awt.event.MouseEvent e) {
                            imageClicked(e);
                        }
                    });
        
        
    }
       
    private void setImage(int index){
        String path = "C:\\Users\\subedipiyush\\Documents\\NetBeansProjects\\FaceAnnotation1\\src\\images\\faces database\\"+a[index]+".jpg";
        
        //BufferedImage img = new BufferedImage(180, 180, BufferedImage.TYPE_INT_RGB);
        try {
            image = ImageIO.read(new File(path));
        } catch (IOException ex) {
            Logger.getLogger(jPanel1.class.getName()).log(Level.SEVERE, null, ex);
        }
        imagelabel = new JLabel(new ImageIcon(image));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void imageClicked(java.awt.event.MouseEvent evt){
        clicked = true;
        x = evt.getX() - 3;
        y = evt.getY() - 3;
        System.out.println(x+" "+y);
    }
    public void jButton1ActionPerformed(java.awt.event.ActionEvent evt){
        index = (index  + 1) % 12;
        setImage(index);
    }
   
        
   /* @Override
    public void paint(Graphics g) {
        super.paint(g);
        g.drawImage(image,20,20,160,160,this);
        if(clicked)
        {
           g.setColor(Color.red); //Setting color to red
           g.fillOval(x, y, 6, 6);
        }
        g.dispose();
        repaint();
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
